package com.zxc.network_coding.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zxc.network_coding.entity.File;
import com.zxc.network_coding.entity.History;
import com.zxc.network_coding.entity.Receive;
import com.zxc.network_coding.entity.Send;

import com.zxc.network_coding.dao.FileDao;
import com.zxc.network_coding.dao.HistoryDao;
import com.zxc.network_coding.dao.ReceiveDao;
import com.zxc.network_coding.dao.SendDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fileDaoConfig;
    private final DaoConfig historyDaoConfig;
    private final DaoConfig receiveDaoConfig;
    private final DaoConfig sendDaoConfig;

    private final FileDao fileDao;
    private final HistoryDao historyDao;
    private final ReceiveDao receiveDao;
    private final SendDao sendDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fileDaoConfig = daoConfigMap.get(FileDao.class).clone();
        fileDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        receiveDaoConfig = daoConfigMap.get(ReceiveDao.class).clone();
        receiveDaoConfig.initIdentityScope(type);

        sendDaoConfig = daoConfigMap.get(SendDao.class).clone();
        sendDaoConfig.initIdentityScope(type);

        fileDao = new FileDao(fileDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);
        receiveDao = new ReceiveDao(receiveDaoConfig, this);
        sendDao = new SendDao(sendDaoConfig, this);

        registerDao(File.class, fileDao);
        registerDao(History.class, historyDao);
        registerDao(Receive.class, receiveDao);
        registerDao(Send.class, sendDao);
    }
    
    public void clear() {
        fileDaoConfig.clearIdentityScope();
        historyDaoConfig.clearIdentityScope();
        receiveDaoConfig.clearIdentityScope();
        sendDaoConfig.clearIdentityScope();
    }

    public FileDao getFileDao() {
        return fileDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

    public ReceiveDao getReceiveDao() {
        return receiveDao;
    }

    public SendDao getSendDao() {
        return sendDao;
    }

}
