package com.zxc.network_coding.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zxc.network_coding.entity.File;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FILE".
*/
public class FileDao extends AbstractDao<File, Long> {

    public static final String TABLENAME = "FILE";

    /**
     * Properties of entity File.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FileName = new Property(1, String.class, "fileName", false, "FILE_NAME");
        public final static Property FilePath = new Property(2, String.class, "filePath", false, "FILE_PATH");
        public final static Property IsBackup = new Property(3, boolean.class, "isBackup", false, "IS_BACKUP");
        public final static Property Md5 = new Property(4, String.class, "md5", false, "MD5");
        public final static Property Hash = new Property(5, String.class, "hash", false, "HASH");
        public final static Property Tag = new Property(6, int.class, "tag", false, "TAG");
        public final static Property Size = new Property(7, long.class, "size", false, "SIZE");
    }


    public FileDao(DaoConfig config) {
        super(config);
    }
    
    public FileDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FILE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"FILE_NAME\" TEXT," + // 1: fileName
                "\"FILE_PATH\" TEXT," + // 2: filePath
                "\"IS_BACKUP\" INTEGER NOT NULL ," + // 3: isBackup
                "\"MD5\" TEXT," + // 4: md5
                "\"HASH\" TEXT," + // 5: hash
                "\"TAG\" INTEGER NOT NULL ," + // 6: tag
                "\"SIZE\" INTEGER NOT NULL );"); // 7: size
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FILE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, File entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(2, fileName);
        }
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(3, filePath);
        }
        stmt.bindLong(4, entity.getIsBackup() ? 1L: 0L);
 
        String md5 = entity.getMd5();
        if (md5 != null) {
            stmt.bindString(5, md5);
        }
 
        String hash = entity.getHash();
        if (hash != null) {
            stmt.bindString(6, hash);
        }
        stmt.bindLong(7, entity.getTag());
        stmt.bindLong(8, entity.getSize());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, File entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(2, fileName);
        }
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(3, filePath);
        }
        stmt.bindLong(4, entity.getIsBackup() ? 1L: 0L);
 
        String md5 = entity.getMd5();
        if (md5 != null) {
            stmt.bindString(5, md5);
        }
 
        String hash = entity.getHash();
        if (hash != null) {
            stmt.bindString(6, hash);
        }
        stmt.bindLong(7, entity.getTag());
        stmt.bindLong(8, entity.getSize());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public File readEntity(Cursor cursor, int offset) {
        File entity = new File( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // fileName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // filePath
            cursor.getShort(offset + 3) != 0, // isBackup
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // md5
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // hash
            cursor.getInt(offset + 6), // tag
            cursor.getLong(offset + 7) // size
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, File entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFileName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFilePath(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIsBackup(cursor.getShort(offset + 3) != 0);
        entity.setMd5(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setHash(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTag(cursor.getInt(offset + 6));
        entity.setSize(cursor.getLong(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(File entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(File entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(File entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
