package com.zxc.network_coding.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zxc.network_coding.entity.Converter.TransmitConverter;
import com.zxc.network_coding.entity.File;

import com.zxc.network_coding.entity.Receive;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RECEIVE".
*/
public class ReceiveDao extends AbstractDao<Receive, Long> {

    public static final String TABLENAME = "RECEIVE";

    /**
     * Properties of entity Receive.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FileId = new Property(1, Long.class, "fileId", false, "FILE_ID");
        public final static Property BackupFileId = new Property(2, Long.class, "backupFileId", false, "BACKUP_FILE_ID");
        public final static Property IsBackup = new Property(3, boolean.class, "isBackup", false, "IS_BACKUP");
        public final static Property Split = new Property(4, int.class, "split", false, "SPLIT");
        public final static Property Transmit = new Property(5, byte[].class, "transmit", false, "TRANSMIT");
        public final static Property FileIdCode = new Property(6, String.class, "fileIdCode", false, "FILE_ID_CODE");
        public final static Property StartDate = new Property(7, java.util.Date.class, "startDate", false, "START_DATE");
        public final static Property EndDate = new Property(8, java.util.Date.class, "endDate", false, "END_DATE");
        public final static Property RestartDate = new Property(9, java.util.Date.class, "restartDate", false, "RESTART_DATE");
    }

    private DaoSession daoSession;

    private final TransmitConverter transmitConverter = new TransmitConverter();

    public ReceiveDao(DaoConfig config) {
        super(config);
    }
    
    public ReceiveDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RECEIVE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"FILE_ID\" INTEGER," + // 1: fileId
                "\"BACKUP_FILE_ID\" INTEGER," + // 2: backupFileId
                "\"IS_BACKUP\" INTEGER NOT NULL ," + // 3: isBackup
                "\"SPLIT\" INTEGER NOT NULL ," + // 4: split
                "\"TRANSMIT\" BLOB," + // 5: transmit
                "\"FILE_ID_CODE\" TEXT," + // 6: fileIdCode
                "\"START_DATE\" INTEGER," + // 7: startDate
                "\"END_DATE\" INTEGER," + // 8: endDate
                "\"RESTART_DATE\" INTEGER);"); // 9: restartDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RECEIVE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Receive entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long fileId = entity.getFileId();
        if (fileId != null) {
            stmt.bindLong(2, fileId);
        }
 
        Long backupFileId = entity.getBackupFileId();
        if (backupFileId != null) {
            stmt.bindLong(3, backupFileId);
        }
        stmt.bindLong(4, entity.getIsBackup() ? 1L: 0L);
        stmt.bindLong(5, entity.getSplit());
 
        int[] transmit = entity.getTransmit();
        if (transmit != null) {
            stmt.bindBlob(6, transmitConverter.convertToDatabaseValue(transmit));
        }
 
        String fileIdCode = entity.getFileIdCode();
        if (fileIdCode != null) {
            stmt.bindString(7, fileIdCode);
        }
 
        java.util.Date startDate = entity.getStartDate();
        if (startDate != null) {
            stmt.bindLong(8, startDate.getTime());
        }
 
        java.util.Date endDate = entity.getEndDate();
        if (endDate != null) {
            stmt.bindLong(9, endDate.getTime());
        }
 
        java.util.Date restartDate = entity.getRestartDate();
        if (restartDate != null) {
            stmt.bindLong(10, restartDate.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Receive entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long fileId = entity.getFileId();
        if (fileId != null) {
            stmt.bindLong(2, fileId);
        }
 
        Long backupFileId = entity.getBackupFileId();
        if (backupFileId != null) {
            stmt.bindLong(3, backupFileId);
        }
        stmt.bindLong(4, entity.getIsBackup() ? 1L: 0L);
        stmt.bindLong(5, entity.getSplit());
 
        int[] transmit = entity.getTransmit();
        if (transmit != null) {
            stmt.bindBlob(6, transmitConverter.convertToDatabaseValue(transmit));
        }
 
        String fileIdCode = entity.getFileIdCode();
        if (fileIdCode != null) {
            stmt.bindString(7, fileIdCode);
        }
 
        java.util.Date startDate = entity.getStartDate();
        if (startDate != null) {
            stmt.bindLong(8, startDate.getTime());
        }
 
        java.util.Date endDate = entity.getEndDate();
        if (endDate != null) {
            stmt.bindLong(9, endDate.getTime());
        }
 
        java.util.Date restartDate = entity.getRestartDate();
        if (restartDate != null) {
            stmt.bindLong(10, restartDate.getTime());
        }
    }

    @Override
    protected final void attachEntity(Receive entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Receive readEntity(Cursor cursor, int offset) {
        Receive entity = new Receive( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // fileId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // backupFileId
            cursor.getShort(offset + 3) != 0, // isBackup
            cursor.getInt(offset + 4), // split
            cursor.isNull(offset + 5) ? null : transmitConverter.convertToEntityProperty(cursor.getBlob(offset + 5)), // transmit
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // fileIdCode
            cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)), // startDate
            cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)), // endDate
            cursor.isNull(offset + 9) ? null : new java.util.Date(cursor.getLong(offset + 9)) // restartDate
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Receive entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFileId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setBackupFileId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setIsBackup(cursor.getShort(offset + 3) != 0);
        entity.setSplit(cursor.getInt(offset + 4));
        entity.setTransmit(cursor.isNull(offset + 5) ? null : transmitConverter.convertToEntityProperty(cursor.getBlob(offset + 5)));
        entity.setFileIdCode(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setStartDate(cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)));
        entity.setEndDate(cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)));
        entity.setRestartDate(cursor.isNull(offset + 9) ? null : new java.util.Date(cursor.getLong(offset + 9)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Receive entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Receive entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Receive entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getFileDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getFileDao().getAllColumns());
            builder.append(" FROM RECEIVE T");
            builder.append(" LEFT JOIN FILE T0 ON T.\"FILE_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN FILE T1 ON T.\"BACKUP_FILE_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Receive loadCurrentDeep(Cursor cursor, boolean lock) {
        Receive entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        File file = loadCurrentOther(daoSession.getFileDao(), cursor, offset);
        entity.setFile(file);
        offset += daoSession.getFileDao().getAllColumns().length;

        File backupFile = loadCurrentOther(daoSession.getFileDao(), cursor, offset);
        entity.setBackupFile(backupFile);

        return entity;    
    }

    public Receive loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Receive> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Receive> list = new ArrayList<Receive>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Receive> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Receive> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
